server:
  port: 7082

spring:
  datasource:
    url: jdbc:mysql://192.168.0.110:3306/uni_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&failOverReadOnly=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  redis:
    database: 1
    host: 192.168.0.110
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 5000
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: false
  mvc:
    servlet:
      path: /uni-register
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

logging:
  level:
    root: warn
    com: info
  file:
    name: logs/uni-register.log